//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/enmanuelreynoso/Documents/repos/lenguajeAutomatas/gramatica/gramaticaAutomata.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class gramaticaAutomataLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, TipoAutomata=12, ID=13, DIGITO=14, WS=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "TipoAutomata", "ID", "DIGITO", "WS"
	};


	public gramaticaAutomataLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public gramaticaAutomataLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Automata:'", "'Tipo:'", "'Inicio:'", "'Aceptacion:'", "'{'", "'}'", 
		"'Transiciones:'", "'->'", "':'", "'vacio'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"TipoAutomata", "ID", "DIGITO", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "gramaticaAutomata.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static gramaticaAutomataLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '\x91', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x80', '\n', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x84', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', '\x87', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x6', '\x10', '\x8C', '\n', '\x10', '\r', '\x10', '\xE', 
		'\x10', '\x8D', '\x3', '\x10', '\x3', '\x10', '\x2', '\x2', '\x11', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '\x3', '\x2', '\x6', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x93', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x3', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '+', '\x3', '\x2', '\x2', '\x2', '\a', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x39', '\x3', '\x2', '\x2', '\x2', '\v', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\r', 'G', '\x3', '\x2', '\x2', '\x2', '\xF', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\x11', 'W', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\x15', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x62', '\x3', '\x2', '\x2', '\x2', '\x19', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', '\x81', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'!', '\"', '\a', '\x43', '\x2', '\x2', '\"', '#', '\a', 'w', '\x2', '\x2', 
		'#', '$', '\a', 'v', '\x2', '\x2', '$', '%', '\a', 'q', '\x2', '\x2', 
		'%', '&', '\a', 'o', '\x2', '\x2', '&', '\'', '\a', '\x63', '\x2', '\x2', 
		'\'', '(', '\a', 'v', '\x2', '\x2', '(', ')', '\a', '\x63', '\x2', '\x2', 
		')', '*', '\a', '<', '\x2', '\x2', '*', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'+', ',', '\a', 'V', '\x2', '\x2', ',', '-', '\a', 'k', '\x2', '\x2', 
		'-', '.', '\a', 'r', '\x2', '\x2', '.', '/', '\a', 'q', '\x2', '\x2', 
		'/', '\x30', '\a', '<', '\x2', '\x2', '\x30', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x32', '\a', 'K', '\x2', '\x2', '\x32', '\x33', '\a', 
		'p', '\x2', '\x2', '\x33', '\x34', '\a', 'k', '\x2', '\x2', '\x34', '\x35', 
		'\a', '\x65', '\x2', '\x2', '\x35', '\x36', '\a', 'k', '\x2', '\x2', '\x36', 
		'\x37', '\a', 'q', '\x2', '\x2', '\x37', '\x38', '\a', '<', '\x2', '\x2', 
		'\x38', '\b', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '\x43', '\x2', 
		'\x2', ':', ';', '\a', '\x65', '\x2', '\x2', ';', '<', '\a', 'g', '\x2', 
		'\x2', '<', '=', '\a', 'r', '\x2', '\x2', '=', '>', '\a', 'v', '\x2', 
		'\x2', '>', '?', '\a', '\x63', '\x2', '\x2', '?', '@', '\a', '\x65', '\x2', 
		'\x2', '@', '\x41', '\a', 'k', '\x2', '\x2', '\x41', '\x42', '\a', 'q', 
		'\x2', '\x2', '\x42', '\x43', '\a', 'p', '\x2', '\x2', '\x43', '\x44', 
		'\a', '<', '\x2', '\x2', '\x44', '\n', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '}', '\x2', '\x2', '\x46', '\f', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\a', '\x7F', '\x2', '\x2', 'H', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', 'V', '\x2', '\x2', 'J', 'K', '\a', 't', '\x2', 
		'\x2', 'K', 'L', '\a', '\x63', '\x2', '\x2', 'L', 'M', '\a', 'p', '\x2', 
		'\x2', 'M', 'N', '\a', 'u', '\x2', '\x2', 'N', 'O', '\a', 'k', '\x2', 
		'\x2', 'O', 'P', '\a', '\x65', '\x2', '\x2', 'P', 'Q', '\a', 'k', '\x2', 
		'\x2', 'Q', 'R', '\a', 'q', '\x2', '\x2', 'R', 'S', '\a', 'p', '\x2', 
		'\x2', 'S', 'T', '\a', 'g', '\x2', '\x2', 'T', 'U', '\a', 'u', '\x2', 
		'\x2', 'U', 'V', '\a', '<', '\x2', '\x2', 'V', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', '/', '\x2', '\x2', 'X', 'Y', '\a', '@', '\x2', 
		'\x2', 'Y', '\x12', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '<', '\x2', 
		'\x2', '[', '\x14', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', 'x', 
		'\x2', '\x2', ']', '^', '\a', '\x63', '\x2', '\x2', '^', '_', '\a', '\x65', 
		'\x2', '\x2', '_', '`', '\a', 'k', '\x2', '\x2', '`', '\x61', '\a', 'q', 
		'\x2', '\x2', '\x61', '\x16', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', '.', '\x2', '\x2', '\x63', '\x18', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', '\x66', '\x2', '\x2', '\x65', '\x66', '\a', 'g', '\x2', 
		'\x2', '\x66', 'g', '\a', 'v', '\x2', '\x2', 'g', 'h', '\a', 'g', '\x2', 
		'\x2', 'h', 'i', '\a', 't', '\x2', '\x2', 'i', 'j', '\a', 'o', '\x2', 
		'\x2', 'j', 'k', '\a', 'k', '\x2', '\x2', 'k', 'l', '\a', 'p', '\x2', 
		'\x2', 'l', 'm', '\a', 'k', '\x2', '\x2', 'm', 'n', '\a', 'u', '\x2', 
		'\x2', 'n', 'o', '\a', 'v', '\x2', '\x2', 'o', '\x80', '\a', '\x63', '\x2', 
		'\x2', 'p', 'q', '\a', 'p', '\x2', '\x2', 'q', 'r', '\a', 'q', '\x2', 
		'\x2', 'r', 's', '\a', '\x61', '\x2', '\x2', 's', 't', '\a', '\x66', '\x2', 
		'\x2', 't', 'u', '\a', 'g', '\x2', '\x2', 'u', 'v', '\a', 'v', '\x2', 
		'\x2', 'v', 'w', '\a', 'g', '\x2', '\x2', 'w', 'x', '\a', 't', '\x2', 
		'\x2', 'x', 'y', '\a', 'o', '\x2', '\x2', 'y', 'z', '\a', 'k', '\x2', 
		'\x2', 'z', '{', '\a', 'p', '\x2', '\x2', '{', '|', '\a', 'k', '\x2', 
		'\x2', '|', '}', '\a', 'u', '\x2', '\x2', '}', '~', '\a', 'v', '\x2', 
		'\x2', '~', '\x80', '\a', '\x63', '\x2', '\x2', '\x7F', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', 'p', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x81', '\x85', '\t', '\x2', '\x2', 
		'\x2', '\x82', '\x84', '\t', '\x3', '\x2', '\x2', '\x83', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x87', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x87', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x89', '\t', '\x4', '\x2', '\x2', '\x89', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\t', '\x5', '\x2', 
		'\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\b', '\x10', '\x2', '\x2', '\x90', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '\x2', '\x7F', '\x85', '\x8D', '\x3', '\b', 
		'\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
